# Generated by Django 5.0 on 2024-01-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_oderitem_oder_remove_oderitem_product_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder',
            new_name='order',
        ),
    ]
